### PR TITLE
feat(components): Custom viewport detection

### PR DESCRIPTION
**Pull request by n-sviridenko**

### CODE REVIEW

**Comment by n-sviridenko** [comment]
We have a use-case which is not covered by `preTriggerRatio`.

**Comment by n-sviridenko** [comment]
@ognen @andon @bevkoski

**Comment by bevkoski** [comment]
Hi @n-sviridenko,

I tested out your implementation and it looks fine: https://snack.expo.io/@bevkoski/viewport-aware-lazy-loading---horizontal

What is missing is an update of the docs. It would be great if you can extend [this](https://github.com/netceteragroup/skele/blob/4f88275fd80047ed7374024e3c3eb68377904b95/packages/components/README.md#usage-1) example with:
```javascript
const ViewportAwareImage = Viewport.Aware(Image)
// const ViewportAwareImage = Viewport.Aware(Image, {
//   isInViewport: (...params) => false // custom viewport detection
// })
```

Moreover, you can update the default `isInViewport` to receive a single object as an argument (instead of a list of arguments), so that custom viewport detection overrides can be done more easily.

Out of curiosity - could you please describe the use case which is not covered by `preTriggerRatio`?

**Review by bevkoski — CHANGES_REQUESTED** [review]
Hi @n-sviridenko,

I tested out your implementation and it looks fine: https://snack.expo.io/@bevkoski/viewport-aware-lazy-loading---horizontal

What is missing is an update of the docs. It would be great if you can extend [this](https://github.com/netceteragroup/skele/blob/4f88275fd80047ed7374024e3c3eb68377904b95/packages/components/README.md#usage-1) example with:
```javascript
const ViewportAwareImage = Viewport.Aware(Image)
// const ViewportAwareImage = Viewport.Aware(Image, {
//   isInViewport: (...params) => false // custom viewport detection
// })
```

Moreover, you can update the default `isInViewport` to receive a single object as an argument (instead of a list of arguments), so that custom viewport detection overrides can be done more easily.

Out of curiosity - could you please describe the use case which is not covered by `preTriggerRatio`?

**Pull request closed without merging**
